### PR TITLE
typo: 'COMPLETED_STATE'

### PR DESCRIPTION
**Pull request by BarisX**

### CODE REVIEW

**Review by thomas545 — APPROVED** [review]
Thank you

**Comment by thomas545** [comment]
@BarisX you have to push migration file, you forgot it

**Review by thomas545 — CHANGES_REQUESTED** [review]
you have to add migration file

**Comment by BarisX** [comment]
should you do `migrate` instead of me? there are a lot of lybraries and i currently solved 3 of them. i still get errors on installing requirements. it is hard to migrate for now.

**Comment by thomas545** [comment]
@BarisX sure i will thank you

**Comment by BarisX** [comment]
also thanks you

**Pull request merged**
